In [1]:
import torch
import numpy as np

In [2]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [4]:
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.1342, 0.8478],
        [0.4156, 0.5969]])


In [5]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))

tensor([[0.9948, 0.0378, 0.5061],
        [0.4468, 0.4558, 0.0942]])
<class 'torch.Tensor'>


In [6]:
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device

tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.2973, 0.8964, 0.8680, 0.7697],
        [0.6547, 0.6143, 0.4195, 0.5790],
        [0.6966, 0.2908, 0.9431, 0.4890]])


device(type='cpu')